version: '3.7'
services:
  mongo_container:
    image: mongo:latest
    container_name: 'my-mongo-container'
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_volume:/data/db # mapping volume database to external container
      - ./dump:/dump:ro # source database, used when restore or import database
      - ./backup:/backup # used when backup database  

volumes:
  mongodb_data_volume:
